### ISSUE TITLE
Epoch does not work properly on Wayland with screen scaling

### ISSUE THREAD

**Issue by cmnrd** [lf-lang/epoch#12]
I am using a setup with Wayland where I have different scaling factors on each of my screens. If I open Epoch in this setup, it looks like this:
![Screenshot_20230306_160703](https://user-images.githubusercontent.com/6460123/223149890-ca622371-cfc7-40a3-a783-8294187566d8.png)

I have to completely disaple scree scaling to work with Epoch. I suspect that this is an Eclipse problem, but we should keep track of this issue nonetheless.

**Comment by lhstrh** [comment]
I've seen this behavior with Eclipse for years. Since Epoch is based on Eclipse, I have no reason to believe that _we_ can fix this.
