### ISSUE TITLE
Epoch cannot be updated

### ISSUE THREAD

**Issue by edwardalee** [lf-lang/epoch#18]
Epoch cannot be updated. When I do `git pull`, I get this:
```
Errors during submodule fetch:
	org.lflang/src/lib/c/reactor-c
Errors during submodule fetch:
	org.lflang/lingua-franca
```
I suspect this is due to the directory reorganization of lingua-franca, hence I'm assigning this @cmnrd to finish that job.

Also, there are no "For Developer" instructions on this page explaining how to update Epoch:

https://www.lf-lang.org/docs/handbook/epoch-ide

**Comment by cmnrd** [comment]
Apparently git does not like so much when submodules are moved around. It should work fine if you do a fresh clone of the epoch repo. Alternatively, the following should resolve the problem:
```
rm -r org.lflang/src/lib
rm -r org.lflang/lingua-franca
git submodule update --init --recursive
```
