### ISSUE TITLE
Fix Java version in Wiki

### ISSUE THREAD

**Issue by AneesHl** [lf-lang/epoch#27]
Java versions > 17 are not supported (yet) by LF, but the Wiki states Java 17 or higher on multiple lines.

Since Pull-requests are not possible for Wikis on GitHub, [Developer-Eclipse-Setup-with-Oomph.md](https://github.com/lf-lang/epoch/files/12301257/Developer-Eclipse-Setup-with-Oomph.md) contains my proposed fix.

**Comment by cmnrd** [comment]
Thanks! I made the change in the wiki page.
