### ISSUE TITLE
Update README.md to describe this repo

### ISSUE THREAD

**Issue by lhstrh** [lf-lang/epoch#3]
See https://github.com/lf-lang/lingua-franca/pull/1482.

**Comment by lhstrh** [comment]
Closing this because it's done, but tagging @edwardalee for review.

**Comment by edwardalee** [comment]
The [Epoch webpage](https://www.lf-lang.org/docs/handbook/epoch-ide) needs a "For developers" section like what is on the [VS Code extension webpage](https://www.lf-lang.org/docs/handbook/code-extension).

**Comment by lhstrh** [comment]
OK, created an issue in the website repo.
