### ISSUE TITLE
The snapshot version is outdated

### ISSUE THREAD

**Issue by cmnrd** [lf-lang/epoch#45]
When launching the nightly build (and I guess also when building from source) the splash screen still shows "0.4.1-SNAPSHOT".

@lhstrh I guess this also needs to be changed somewhere as part of the release workflow.

**Comment by lhstrh** [comment]
The release updated the splash screen, as you can see here: https://github.com/lf-lang/epoch/blob/e606c42eeb51f814fa5aef77f43c58417a687777/org.lflang.product/splash.bmp

I'm not sure about the nightly releases. I'll look into that.

**Comment by lhstrh** [comment]
Snapshot version was also created correctly: https://raw.githubusercontent.com/lf-lang/epoch/1f7e4b401a8ced166a621df053b95bb99d6f5e02/org.lflang.product/splash.bmp

**Comment by lhstrh** [comment]
I've also confirmed that the splash screen in the released artifacts displays the correct version, unlike what's reported in https://github.com/lf-lang/lf-lang.github.io/issues/158
