### ISSUE TITLE
NORMAL validation is no longer invoked on saving the file

### ISSUE THREAD

**Issue by edwardalee** [lf-lang/epoch#7]
It used to be that when saving a file in Epoch, any validation function labeled NORMAL would be invoked. This is no longer the case (in master). LFValidator has this code:
```
    @Check(FAST)
    def checkModel(Model model) {
        // Since we're doing a fast check, we only want to update
        // if the model info hasn't been initialized yet. If it has,
        // we use the old information and update it during a normal
        // check (see below).
        if (!info.updated) {
            info.update(model, errorReporter)
        }
    }

    @Check(NORMAL)
    def updateModelInfo(Model model) {
        info.update(model, errorReporter)
    }
```
You can set a breakpoint in the second function and verify that it is not invoked on file save. It is invoked when you invoke the code generator using the button that @a-sr added.

With the current behavior, the above functions are incorrect.  The FAST checkModel function will not update the model when you make a change, making it fairly useless.

**Comment by lhstrh** [comment]
Closing this, assuming that https://github.com/lf-lang/lingua-franca/pull/894 fixes the problem. If not, feel free to reopen.
