### ISSUE TITLE
Error markers not being cleared in Epoch after showing up in code generation

### ISSUE THREAD

**Issue by edwardalee** [lf-lang/epoch#9]
@a-sr: this PR is now in a state where there is a remaining problem that we don't seem able to fix. 

If an error marker is added through validation triggered by the Compile button, then the marker will not be removed if the error is fixed (even if the document is saved) until the Compile action is invoked again. It appears that validator instances only remove markers that they have added, leaving markers added by others untouched. I attempted removing the markers explicitly in `LFValidator.checkModel()` but the available `eResource` is apparently not an `iResource` and can therefore not be cast to an `iFile` (which has the `deleteMarkers()` method). Any help with this would be greatly appreciated!

_Originally posted by @lhstrh in https://github.com/lf-lang/lingua-franca/issues/967#issuecomment-1045355099_

**Comment by lhstrh** [comment]
@edwardalee, is this still an issue, or has it been fixed?

**Comment by edwardalee** [comment]
I'm not sure whether this issue still exists because now we have a worse issue where markers don't even appear. When compiling [BrowserUI.lf](https://github.com/lf-lang/examples-lingua-franca/blob/01060c52e64e44a7851266028782b37aed6789ed/C/src/browser-ui/BrowserUI.lf) in Epoch (rebuilt using current master), I get this:
```
WARNING: Setting markers in the IDE failed:
org.eclipse.core.internal.resources.ResourceException: Resource '/Examples/src-gen/C/src/browser-ui/BrowserUI/_serverui.c' does not exist.
Error (Range: [(0, 0), (0, 0))): Error in imported file: /Users/eal/git/examples-lingua-franca/src-gen/C/src/browser-ui/BrowserUI/_serverui.c
Error (Range: [(195, 0), (195, 0))):  error: use of undeclared identifier 'LF_SOURCE_DIRECTORY'
    char* file_path = (char *) malloc(strlen(LF_SOURCE_DIRECTORY) + strlen(path) + 2);
                                             ^
Error (Range: [(0, 0), (0, 0))): Error in imported file: /Users/eal/git/examples-lingua-franca/src-gen/C/src/browser-ui/BrowserUI/BrowserUI.c
Error (Range: [(198, 0), (198, 0))):  error: use of undeclared identifier 'LF_SOURCE_DIRECTORY'
    sprintf(file_path, "%s%s%s", LF_SOURCE_DIRECTORY, LF_FILE_SEPARATOR, path);
                                 ^
Error (Range: [(0, 0), (0, 0))): Error in imported file: /Users/eal/git/examples-lingua-franca/src-gen/C/src/browser-ui/BrowserUI/BrowserUI.c
Error (Range: [(198, 0), (198, 0))):  error: use of undeclared identifier 'LF_FILE_SEPARATOR'
    sprintf(file_path, "%s%s%s", LF_SOURCE_DIRECTORY, LF_FILE_SEPARATOR, path);
                                                      ^
3 errors generated.
```

**Comment by lhstrh** [comment]
I don't know what to do about this. Perhaps @a-sr has an idea?

The problem is that we cannot test Epoch in CI, so we have no idea that things break, and when we get a bug report like this one, we have no clue when/why/how this happened.

Are you sure that you built Epoch with all the submodules updated recursively?

**Comment by edwardalee** [comment]
Part of any major refactoring job is making sure the tools still work. At least a smoke test is needed. Epoch doesn't even compile test/C/HelloWorld.lf (output is below). I'm assigning this to @cmnrd and @petervdonovan because I suspect it was one of their refactorings that broke Epoch.

```
Information: Generating code for: platform:/resource/TestC/src/HelloWorld.lf
Information: Generation mode: EPOCH
Information: Generating sources into: /Users/eal/lingua-franca-intellij/test/C/src-gen/HelloWorld
Error: A required resource could not be found on the classpath or is an empty directory: /lib/c/reactor-c/core
Perhaps a git submodule is missing or not up to date.
Try running 'git submodule update --init --recursive' and rebuild.
Also see https://www.lf-lang.org/docs/handbook/developer-setup.

--- Current working directory: /Users/eal/lingua-franca-intellij/test/C/src-gen/HelloWorld/build
--- Executing command: cmake -DLF_REACTION_GRAPH_BREADTH=1 -DLF_THREADED=1 -DNUMBER_OF_WORKERS=0 -DSCHEDULER=NP -DLOG_LEVEL=0 -DLF_TRACE=HelloWorldTrace -DCMAKE_BUILD_TYPE=Debug -DCMAKE_INSTALL_PREFIX=/Users/eal/lingua-franca-intellij/test/C -DCMAKE_INSTALL_BINDIR=bin -DLF_FILE_SEPARATOR="/" -DLF_SOURCE_DIRECTORY="/Users/eal/lingua-franca-intellij/test/C/src" -DLF_PACKAGE_DIRECTORY="/Users/eal/lingua-franca-intellij/test/C" /Users/eal/lingua-franca-intellij/test/C/src-gen/HelloWorld
-- The C compiler identification is AppleClang 14.0.0.14000029
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Looking for pthread.h
CMake Error at CMakeLists.txt:28 (add_subdirectory):
  add_subdirectory given source "core" which is not an existing directory.


-- Looking for pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Success
-- Found Threads: TRUE  
-- Configuring incomplete, errors occurred!
See also "/Users/eal/lingua-franca-intellij/test/C/src-gen/HelloWorld/build/CMakeFiles/CMakeOutput.log".
See also "/Users/eal/lingua-franca-intellij/test/C/src-gen/HelloWorld/build/CMakeFiles/CMakeError.log".
Warning (Range: [(0, 0), (0, 0))): CMake Error at CMakeLists.txt:28 (add_subdirectory):
  add_subdirectory given source "core" which is not an existing directory.
Warning (Range: [(0, 0), (0, 0))): Warning in imported file: /Users/eal/lingua-franca-intellij/test/C/src/HelloWorld.lf
```

**Comment by a-sr** [comment]
I cannot reproduce the above errors. Both LF files compile fine in my Epoch built with the main branch.
We also have a CI test for compiling the LF exmaple programs in Epoch and [it did not report errors](https://github.com/lf-lang/epoch/actions/runs/5478403276/jobs/9978825270#step:7:18744).

The error message mentions a potential problem with submodules, maybe they are in an incorrect state on your system?

**Comment by edwardalee** [comment]
Ugh.  I thought I was using a fresh clone, but instead I was using an old clone with the submodules replaced. Only a fresh clone works. The original issue is still present, but I don't actually think it's a real issue, so I'm closing this.
